
default:
  image: ${TAK_REGISTRY_HOST}/devsecops/android-builder-image:${ANDROID_BUILDER_TAG}

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:

  - regex=".*maintenance-([0-9]+\.[0-9]).*";
    if [[ ${CI_COMMIT_REF_NAME} =~ ${regex} ]]; then
    SDK_BRANCH_NAME="maintenance-${BASH_REMATCH[1]}";
    else
    SDK_BRANCH_NAME="master";
    fi
  - echo "SDK Branch $SDK_BRANCH_NAME"

  - git clone --depth 1 -b $SDK_BRANCH_NAME https://civsdk_builder:_NxPo8NmvzvgNRxaNzH-@git.takmaps.com/sdks/atak-civ.git

stages:
  - build
  - test
  
assembleMilSdkRelease:
  stage: build
  script:
    - pwd .
    - mkdir sdk
    - cp atak-civ/main.jar sdk
    - cp atak-civ/android_keystore sdk
    - cp atak-civ/atak-gradle-takdev.jar sdk
    - find . -name main.jar
    - ./gradlew -Pci --console=plain -Ptakdev.plugin=$PWD/sdk/atak-gradle-takdev.jar lintMilRelease assembleMilRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/

assembleMilOdkRelease:
  stage: build
  script:
    - ./gradlew --console=plain -Pci -Ptakrepo.force=true -Ptakrepo.url=${ARTIFACTORY_URL_APK} -Ptakrepo.user=${ARTIFACTORY_USER} -Ptakrepo.password=${ARTIFACTORY_PASSWORD} assembleMilRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual
  
assembleCivSdkRelease:
  stage: build
  script:
    - mkdir sdk
    - cp atak-civ/main.jar sdk
    - cp atak-civ/android_keystore sdk
    - cp atak-civ/atak-gradle-takdev.jar sdk
    - ./gradlew -Pci --console=plain -Ptakdev.plugin=$PWD/sdk/atak-gradle-takdev.jar lintCivRelease assembleCivRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual

assembleCivOdkRelease:
  stage: build
  script:
    - ./gradlew --console=plain -Pci -Ptakrepo.force=true -Ptakrepo.url=${ARTIFACTORY_URL_APK} -Ptakrepo.user=${ARTIFACTORY_USER} -Ptakrepo.password=${ARTIFACTORY_PASSWORD} assembleCivRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual
  
testRelease:
  stage: test
  script:
    - mkdir sdk
    - cp atak-civ/main.jar sdk
    - cp atak-civ/android_keystore sdk
    - cp -R atak-civ/espresso .
    - cp atak-civ/atak-gradle-takdev.jar sdk
    - ./gradlew -Pci --console=plain -Ptakdev.plugin=$PWD/sdk/atak-gradle-takdev.jar :app:testMilRelease

